--
-- Name: users; Type: TABLE; Schema: public
--

CREATE TABLE IF NOT EXISTS users
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(128) NOT NULL,
    email       VARCHAR(128) NOT NULL,
    password    VARCHAR(128) NOT NULL,
    created_utc TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_utc TIMESTAMP NULL
    );

--
-- Name: user_roles; Type: TABLE; Schema: public
--

CREATE TABLE IF NOT EXISTS user_roles
(
    user_id   INTEGER NOT NULL,
    user_role VARCHAR(50) NOT NULL,
    PRIMARY KEY (user_id, user_role),
    CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    );

--
-- Name: users_id_idx; Type: INDEX; Schema: public
--

CREATE INDEX IF NOT EXISTS users_id_idx ON users (id);
